### ISSUE TITLE
add new items to /loot

### ISSUE THREAD

**Issue by Nealithh** [Galarzaa90/NabBot#102]
## Platform information
* **Operating system:** 
* **Python version:**

## Bug information
as he doesn't count some loot items that can be sold to the npc 
http://prntscr.com/ju47hc
24 unknown

**Steps to reproduce:**

**Expected result:**

**Actual result:**

**Comment by Galarzaa90** [comment]
Can you send me loot image?

**Comment by Nealithh** [comment]
[image: image.png]


Op di 12 jun. 2018 om 18:38 schreef Allan Galarza <notifications@github.com

**Comment by Galarzaa90** [comment]
@Nealithh I can't see the image, you should try replying directy on GitHub, it's not working through email.

**Comment by Nealithh** [comment]
![image](https://user-images.githubusercontent.com/29667671/41309064-ef54e712-6e7d-11e8-9212-0714108a5165.png)

**Comment by Nealithh** [comment]
ah ye sorry didn't know xD

**Comment by Nealithh** [comment]
most of them are from the area feyrist

**Comment by Galarzaa90** [comment]
It should be fixed now, update to 1.1.1, and delete the file `data\loot.db`, a new one will be generated on startup.
