### ISSUE TITLE
Add characters

### ISSUE THREAD

**Issue by vinioliagui** [Galarzaa90/NabBot#11]
is it possible to add characters that doesn't belong to any of the discord's channel users? I'm trying with the /stalk command but requires a discord username. Also, it seems I can't set two or more worlds in the channel.

**Comment by Galarzaa90** [comment]
For the moment, no. I want to make some kind of watched list, for other people characters, to get messages when they login or logout

And yes, for the moment only one world can be added per discord server.

**Comment by Fcguedes** [comment]
Do you have any idea when the login and logout function will be avaliable?

**Comment by Galarzaa90** [comment]
Watched list was added on commit 3527a56510658c6e481f0c78aee775ca3bca2068 on the rewrite branch.
