### ISSUE TITLE
Owner permissions

### ISSUE THREAD

**Issue by Fcguedes** [Galarzaa90/NabBot#12]
This latest update no longer allows me to use OWNER commands, but I am the creator of the BOT and it can not identify it.
In this case, what should i do?

**Comment by Galarzaa90** [comment]
Did you add your discord user id in **[here](https://github.com/Galarzaa90/NabBot/blob/master/config.py#L42-L45)**? This is what identifies you as the owner.

**Comment by Fcguedes** [comment]
Sorry for my "noob" question, but where i find it?

**Comment by Galarzaa90** [comment]
First, in your discord user settings, go to the **Appearance** section and enable **Developer Mode** there.

![image](https://cloud.githubusercontent.com/assets/12865379/23766482/326fd3a8-04c2-11e7-9a49-89c4effe6b82.png)

Once it has been enabled, right click on your name in a chat or online list and a new option **Copy ID** should appear, that's your user id.
![image](https://cloud.githubusercontent.com/assets/12865379/23766472/271e57b8-04c2-11e7-9c7a-b1c3f55f77a5.png)

**Comment by Fcguedes** [comment]
Oh Thanks :D.
