### ISSUE TITLE
Command to set bot log channel?

### ISSUE THREAD

**Issue by rymaster62** [Galarzaa90/NabBot#16]
I must be missing it somewhere, but when you do /diagnose, the bot gives Ask channel and Log channel as two separate options.  I did /setchannel but it only sets the Ask channel, not the Log channel.

What is the difference between the two channels? I only ask because in the description it says /setchannel is for the bot's announcements, which assigns as the Ask channel.

**Comment by Galarzaa90** [comment]
Announce channel is not the same as ask-channel, in fact ask-channel cannot be changed (per server) yet, only changed in config.

* Ask channel is a channel where command responses are longer and only commands are allowed there, to reduce command spam in other channels a bit. It has to be named #ask-nabbot, unless changed in [config.py](https://github.com/Galarzaa90/NabBot/blob/master/config.py#L14)

* Log channel is a special channel where the bot posts server changes, this is meant to be a private channel only for server admins. It announces there when people register or unregister new chars (even if they did it on pm), when people leave or get kicked and so on. This channel must be named #server-log, unless changed in [config.py](https://github.com/Galarzaa90/NabBot/blob/master/config.py#L16)
![image](https://cloud.githubusercontent.com/assets/12865379/25065276/c5cf98e2-21c1-11e7-83ca-efa3020afaeb.png).

* Announce channel is where the bot will post deaths and level up announcements, the bot uses by default the default server channel, but some people prefer to move it to a specific channel. This setting can be changed per server using /setchannel.

Note that some of the features of NabBot are aimed towards making one single instance of NabBot run in multiple discord servers. My instance of NabBot is running on 3 servers.
