### ISSUE TITLE
RaspberryPi 3 Python Error

### ISSUE THREAD

**Issue by MausiMaus** [Galarzaa90/NabBot#20]
`  Downloading https://github.com/Rapptz/discord.py/archive/master.zip (481kB)
    100% |████████████████████████████████| 491kB 230kB/s 
Collecting pillow
  Using cached Pillow-4.1.1.tar.gz
Collecting psutil
  Using cached psutil-5.2.2.tar.gz
Collecting requests
  Using cached requests-2.14.2-py2.py3-none-any.whl
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice])
  Using cached aiohttp-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-G05q2y/aiohttp/setup.py", line 60, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-G05q2y/aiohttp/
`

Im getting this error over and over again on my RaspberryPi if i try to run:

 `python -m pip install -U https://github.com/Rapptz/discord.py/archive/master.zip#egg=discord.py[voice] pillow psutil requests`

In the direction "/tmp/pip-build-G05q2y/aiohttp/" stands nothing (I got the latest version of raspbian).

**Comment by Galarzaa90** [comment]
You're not running it in python 3.4.2 or higher

**Comment by MausiMaus** [comment]
pi@RespberryPi:~ $ python --version
Python 2.7.9
pi@RaspberryPi:~ $ python3 --version
Python 3.4.2

`python3 -m pip install -U https://github.com/Rapptz/discord.py/archive/master.zip#egg=discord.py[voice] pillow psutil requests `

I just runed this command and it worked fine =)

**Comment by Galarzaa90** [comment]
Perfect :100: 

The `python` parts varies per installatiion, for some it's `py`, for some its `python3`, for some it's `python`. So it's up to the user to use the correct one according to their setup :)
