### ISSUE TITLE
Only reply in bot channel

### ISSUE THREAD

**Issue by MausiMaus** [Galarzaa90/NabBot#21]
Hello,
It would be cool if you could add an entry in the config.py where you can set that the bot will only reply in the ask_channel_name. Its sometimes realy annoying if the normal charoom get spammed by commands =)

Your Mausi Maus

/edit dont mind about changing the title xD

**Comment by knobik** [comment]
this is exacly what i did in my fork... it was annoying to see the commands in #general

**Comment by Galarzaa90** [comment]
This is now implemented in the rewrite branch. With the /ignore command you can ignore any channels you want.

Note that this was already possible to do by changing the bot's permissions, except for the default channel.
Also, by moving permissions it wasn't possible to have the bot make deaths and level announcements on one channel, but ignore commands (cause write permission *requires* read permission).

Also, server administrators can bypass this, the bot will always listen to their commands.
