### ISSUE TITLE
/loot recognized item Onyx Chip as Black Wool

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#30]
![image](https://user-images.githubusercontent.com/1021860/27571926-51f86c80-5adf-11e7-8b21-6fb7ba6f5367.png)
![image](https://user-images.githubusercontent.com/1021860/27571948-6e27993a-5adf-11e7-8b1e-5e432478c897.png)

**Comment by Galarzaa90** [comment]
The images we use are obtained from TibiaWiki, some images are incorrect (they're not aligned exactly like in the client) or have different formats (as they are created by multiple people).

That adding to the fact that image recognition is not perfect, as it has to give some margin for error to compensate for image compression, makes it prone to errors.

Usually new items are more prone to be recognized, but over time (and if people contribute to TibiaWiki) to fix those items, it should be improved.

Mantaining a image database that big would require a lot of effort, so we just rely on TibiaWiki.

**Comment by Galarzaa90** [comment]
@fclaussen 
* Pull changes
* Delete utils/loot.db
* Run NabBot

Those items should cause less problems now.

Thanks @Nezune

**Comment by fclaussen** [comment]
works.
