### ISSUE TITLE
Watched went to bed

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#34]
Yesterday my internet went down, so the bot stopped working.
When it finally came back up, the watched were not working. I then closed and reopened the bot.

A few hours later I noticed that the list was not being updated. It was sending a new message every few minutes.
Not sure why it lost the original message reference.

I solved the issue by deleting the channel and recreating it with `/watched hunteds` and setting the permissions again.

**Comment by Galarzaa90** [comment]
I've seen this happen from time to time. It might be a discord issue, this is how it works:
Everytime the hunted list is updated, it gets the id of the last message (stored on the db), then it gets said message. If it finds it, then it edits that one.

If it doesn't find the message, it creates a new message instead, and saves the new message's id as the new reference, so the next time it updates the new one. This was made to prevent it from crashing if someone deleted the original message.

For some reason is failing to find the previous message, making it send a new message sometimes. I've seen it happen in some servers, but recreating the channel is not neccesary.

**Comment by Galarzaa90** [comment]
I will close this issue as it seems to be inactive, if there's still problems, it will be reopened.

I have been using the watched list for more than a month without issues.
