### ISSUE TITLE
Make /event greate again!

### ISSUE THREAD

**Issue by MausiMaus** [Galarzaa90/NabBot#36]
Hello!
tomorrow there is an poi and inq host on my server so i tried to create an event for the discord. Now the Bot asked me: "Alright, now tell me the start time of the event from now. e.g. 2d1h20m, 2d3h".
I think it could be ways more comfortable if you could say an date like "22/7/17 4pm" or "tomorrow 16pm".

Would be cool :) 
Greetings MausiMaus

**Comment by Galarzaa90** [comment]
I decided to use relative times so it could be universal for anyone using it. Using times like you suggested, would require setting a default timezone, and it would be complicated for people that are not using the same timezone.

The current way, you just set the time based on how long til the event starts, then everyone can see the time in their local time by using /event info <id>

**Comment by MausiMaus** [comment]
hm true but you could use the tibias server save cyclus as an timezone itsself so like "5hrs after the next server save"
