### ISSUE TITLE
/loot not identifying the correct item

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#37]
It was a werebadger trophy, it read a cultish robe.
![image](https://user-images.githubusercontent.com/1021860/28496570-0a56e79c-6f45-11e7-8a90-a53ae3b61f87.png)
![image](https://user-images.githubusercontent.com/1021860/28496575-198c7542-6f45-11e7-982b-131b1a0c114e.png)

**Comment by Nezune** [comment]
Thanks, should be fixed now. You'll have to download the loot_template.db and replace your own loot.db with it for the changes to take effect.
