### ISSUE TITLE
/event improvements

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#38]
It would be nice to have an announcer. When we sub to an event we get a message when the event is about to start, but it would be nice to have it send a message with announcers like **Reminder: {event name} in {time to start}. Sub with /event sub {event id} to receive a notification when it's about to start.**

Would also add an option in the config file to set the periodicity. It would be nice to announce it every few hours so people see it and join in.

Speaking of joining.. A nice feature would be a "join" subcommand. /event join {event id}.

That would allow us to know how many people are going and who is going.
Something like /event participants {event id}.
Maybe replace the sub with the join (if you joined, you are subbed).

**Comment by Galarzaa90** [comment]
Implemented in #74
