### ISSUE TITLE
Gemmed Figurine is worth 3.5k

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#43]
Gemmed Figurine is being considered as no value on /loot.
It is worth 3.5k
http://tibia.wikia.com/wiki/Gemmed_Figurine

**Comment by Galarzaa90** [comment]
Nevermind @Nezune, I think I got it

**Comment by Galarzaa90** [comment]
Fixed @fclaussen, delete your `loot.db` and restart NabBot.
