### ISSUE TITLE
Add the ability to bind a IP-failover or a collection of ips.

### ISSUE THREAD

**Issue by knobik** [Galarzaa90/NabBot#50]
Tibia.com banned my vps ip, i have 2 additional ips in the interface aliases i can use but i cant bind any of that ip to the tibia.com route, so it would be the best if you gave a config option for a ip collection the script would use to ping tibia.com at random. 

example based on wget:

use default ip:
wget whatsmyip.org => 123.123.123.0

use interface alias:
wget whatsmyip.org --bind-address=123.123.123.1 => 123.123.123.1

edit:

aiohttp can be done with:

http://aiohttp.readthedocs.io/en/stable/faq.html#how-to-make-request-from-a-specific-ip-address

```python
conn = aiohttp.TCPConnector(local_addr=('123.123.123.1, 0), loop=loop)
async with aiohttp.ClientSession(connector=conn) as session:
...```

**Comment by Galarzaa90** [comment]
I think I will close this issue as this doesn't seem to be a problem anymore because of TibiaData.

However, if this is still a problem, we can reopen this issue.
