### ISSUE TITLE
use tibiadata.com for scrapping character data.

### ISSUE THREAD

**Issue by knobik** [Galarzaa90/NabBot#51]
You are using the official website to scrap the data about characters etc. But cipsoft has introduced a flood control and bans ip's that scrap to much data even with standard settings. Its a issue that needs to be solved asap as it gives headaches to everyone using your bot. You could port the code to use data out of tibiadata.com which is free to use and reliable.

**Comment by Galarzaa90** [comment]
I didn't know of that site, I'm surprised.

Yes, this has been a huge problem for me. Doesn't affect my bot that much, it's me that's more affected by it when browsing tibia.com myself, although recently I stopped getting 502 errors again.

Anyway, do you know if the jsons are static and being updated after X time, or are they actually being fetched from tibia.com and served to you in json when you check them?

If it's the former, how often are they updated? Are they updated as ~~slow~~ as fast as tibia.com? If that's the case I would definitely replace them.

**Comment by knobik** [comment]
This is not my service, found it by accident. I think the data there is cached but the timeout is low.

**Comment by tobiasehlert** [comment]
Right now the data on tibiadata.com API is realtime (1 request to the API results in 1 request towards tibia.com), but I'm continue to work on this to improve the API when it comes to performance and some other new cool features.

**Comment by knobik** [comment]
Any plans?

**Comment by Galarzaa90** [comment]
Implemented in rewrite, see #64
