### ISSUE TITLE
/bosses command returns no information for Noctera

### ISSUE THREAD

**Issue by Alscara** [Galarzaa90/NabBot#52]
## Platform information
* **Operating system:** Ubuntu 17.04
* **Python version:** 3.6.1
* **Repository branch:** rewrite

## Bug information

/bosses does not work for Noctera. It returns a an empty result. Works for every other world I've tried.

**Steps to reproduce:**: 
/bosses Noctera in server or PM
**Expected result:**
List of bosses as the command intends
**Actual result:**
Markdown containing the text "Bosses for Noctera" and nothing else

**Comment by knobik** [comment]
Same goes for Vita

**Comment by Galarzaa90** [comment]
Ok, can reproduce this for worlds like Tortura, Mortera, Helera, so new worlds in general.
I parse tibiabosses.com for this information, there must be something different in the format of the data presented in those worlds.

**Comment by fclaussen** [comment]
Same thing for Honbra

**Comment by Galarzaa90** [comment]
Finally fixed this, only 3 months later.
