### ISSUE TITLE
/setchannel not working

### ISSUE THREAD

**Issue by Alscara** [Galarzaa90/NabBot#53]
## Platform information
* **Operating system:** Ubuntu 17.04
* **Python version:** 3.6.1
* **Repository branch:** rewrite

## Bug information

/setchannel is not working. It asks if I want to set the channel and then when I say yes, throws an error in the console.

**Steps to reproduce:**: 
/setchannel channelname
yes
**Expected result:**
Channel set
**Actual result:**
2017-09-07 18:17:54,466:INFO: Command by Alscara in #lobby-channel (Carpe Diem): /setchannel tibia-bot
In setchannel:
  File "/home/media1/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/media1/NabBot-CD-rewrite/NabBot/cogs/admin.py", line 447, in set_announce_channel
    " I can see on the list.".format(ctx.guild.default_channel))
AttributeError: 'Guild' object has no attribute 'default_channel'

**Comment by knobik** [comment]
Update your bot, i think Allan already fixed that bug.

**Comment by Alscara** [comment]
Considering I just downloaded the latest rewrite yesterday and also installed all the latest dependencies and version of discord.py yesterday, that advice doesn't help me

**Comment by Galarzaa90** [comment]
@Alscara I forgot to remove `format(ctx.guild.default_channel)`.

It should be fixed now.
