### ISSUE TITLE
NabBot getting down

### ISSUE THREAD

**Issue by diegovicron** [Galarzaa90/NabBot#54]
I have recently re-installed succesfully the bot on a new server. However, it is constantly getting down after a while.

I ran the command "python3 restart.py &" and after a few minutes it gets down again.

Any advice?

**Comment by Galarzaa90** [comment]
I'm going to need more info than that.

Errors? Python version? OS? Rewrite? Master? The stuff on the issue template you deleted.

**Comment by diegovicron** [comment]
Thanks and I am sorry for not providing the details, Allan. 
Well, as a matter of fact, it stopped going down once I changed from "python3 restart.py &" to "python3 restart.py&"... not sure if this is the actual cause but I am closing this issue and, if needed, I will reopen it providing the data.

**Comment by Galarzaa90** [comment]
That's really weird, but I'm glad it works now :ok_hand:
