### ISSUE TITLE
Improvements for /im

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#55]
Having a large guild makes it harder and harder to maintain discord without any spies.
Sometimes someone joins, registers with /im and after a while leaves to another guild but we still get updates from their level ups and deaths and they still have access to discord because nobody noticed he left the guild and removed him from discord

It would be great to set your guild just like setWorld and maybe once a week or on command the bot check the guild members. If he found someone on the /im database that is not on the guild or on the same account as someone from the guild, kicks it.

Right now with a guild of almost 200 members, you can imagine how much work it takes to check up on everyone.

If there's already a similar feature to this, please let me know as I'm going crazy over here 😆

**Comment by Galarzaa90** [comment]
I know what you mean, and I've thought about it. We use roles to to keep certain channels only for our guild members.

What helps, is that we have a channel called #guild-log, were a webhook posts guild updates.
![image](https://user-images.githubusercontent.com/12865379/31245567-9c4dab72-a9bf-11e7-912d-c90291d9ca66.png)

It's a separate script. It's also useful to get updates about other guilds :eyes: 

https://github.com/Galarzaa90/GuildWatcher

I'd stil llike to do something about it for NabBot, not the full GuildWatcher tho.

**Comment by fclaussen** [comment]
I've been using guildwatcher. It's been very helpful.
