### ISSUE TITLE
I can't use /setworld

### ISSUE THREAD

**Issue by Prossaicom** [Galarzaa90/NabBot#56]
I can't use /setworld anywhere, i used /help setworld and says "No command called "setworld" found."
i'm the admin of the server

**Comment by Galarzaa90** [comment]
Do not delete the issue template if it's a bug report. I need to know which branch are you using. I can assume you're using master.

**Comment by Prossaicom** [comment]
yes, i'm using nabBot - master, is this what u need to know?

**Comment by Galarzaa90** [comment]
Any other messages? Any messages on console?

I just tested master branch, and it works fine for me.
![image](https://user-images.githubusercontent.com/12865379/31526571-8aebf8ee-af7c-11e7-89a6-c1aee1159dad.png)

**Comment by Prossaicom** [comment]
i have this problem too, can u help me?
![screenshot_1](https://user-images.githubusercontent.com/32561029/31591339-91cac55e-b1fd-11e7-9e73-72d19f8fd332.png)

**Comment by fclaussen** [comment]
@Prossaicom Please refer to
[https://github.com/Galarzaa90/NabBot#requirements](https://github.com/Galarzaa90/NabBot#requirements)
and
[https://github.com/Galarzaa90/NabBot#installing-and-running](https://github.com/Galarzaa90/NabBot#installing-and-running)

From what I can see on this error, you are missing the **requests** python module.

**Comment by Prossaicom** [comment]
I installed "requests" and now it works fine, thanx everyone :DDD
nice bot, btw
