### ISSUE TITLE
Switched to a VPS

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#57]
I switched to a VPS today instead of running it on my on computer. (Every weekend when I travel I would turn off my pc and people would get angry :P )

Since I'm not experienced with python I google how to let the script running after I closed the ssh connection.

I ended up starting it with `nohup python nabbot.py`

Is that the best/correct approach?

**Comment by Galarzaa90** [comment]
That should work according to this:
https://unix.stackexchange.com/a/4006

I don't know if there's a better way to do it.

What VPS are you using?

**Comment by fclaussen** [comment]
I'm using Digital Ocean with Ubuntu 17.04, $5 month
