### ISSUE TITLE
Bug with findteam filtering

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#59]
## Platform information
* **Operating system:** Ubuntu 17.04
* **Python version:** 3.6.1
* **Repository branch:** rewrite

## Bug information
When using /findteam, if you filter by one vocation and then filter by another without unfiltering first it messes the names.

**Steps to reproduce:**: /findteam Jongun > Filter paladins > Filter knights (without clicking to unfilter paladins)

**Expected result:** You would see something like this 
![image](https://user-images.githubusercontent.com/1021860/31513386-94d4f5c6-af64-11e7-806b-7a001568c443.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/1021860/31513400-a0967538-af64-11e7-9fcf-035372b4d5b8.png)

**Comment by Galarzaa90** [comment]
I see it, and it keeps messing up if you switch pages. Really odd. I'm checking it right now.

**Comment by Galarzaa90** [comment]
**Status update:** Bug still driving me crazy.
I can reproduce it, until I try to debug it, then the bug gets all shy and stops showing.

**Comment by Galarzaa90** [comment]
Here's what discord is showing:
![image](https://user-images.githubusercontent.com/12865379/32075823-c774751c-ba52-11e7-9ae6-b6202d41668b.png)


Here's what python is showing:
![image](https://user-images.githubusercontent.com/12865379/32075866-eb6010e4-ba52-11e7-929b-077369cffe60.png)

**Comment by Tschis** [comment]
I can confirm the problem was present while debugging.

**Comment by Galarzaa90** [comment]
This turned out to be a Discord bug, specifically for the desktop version. Discord is showing the embed incorrectly, the data being sent to the embed is always correct.

This can be tested on a mobile device. If you look at the command side to side on a phone and on a computer, you will see how it starts glitching on the computer, but it will always look fine on mobile.

So sadly, there's nothing I can do.

**Comment by Tschis** [comment]
I tested and confirmed that the problem shows on desktop version of Windows 10 but not on iOS 11.

**Comment by fclaussen** [comment]
This has since been resolved by discord owners. It's not happening anymore.
