### ISSUE TITLE
Track hidden characters

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#63]
I'm trying to understand how something like tibiaring can "find hidden characters" of people. I mean [this](http://www.tibiaring.com/seccAll.php?lang=en).

Do you happen to know the logic behind it? I'm very curious. I tried it on myself, got correct results along with some wrong ones.

If we can figure out how it's done, it's probably a nice special feature to have.

**Comment by Tschis** [comment]
While I do agree this is an interesting problem (technically speaking), I personally find it is not in the best interest of the project. 

Nab is not a war bot and, unless you are fighting a war, this would not bring any meaningful feature for it.

**Comment by Galarzaa90** [comment]
@fclaussen As far as I know it's based on login times, so it requires a lot of data.

If you notice, TibiaRing has a huge database, as they keep track of your complete death history, guild history, transfer history.

So it would require NabBot keeping track of all the characters in a world.
