### ISSUE TITLE
death without level breaks bot

### ISSUE THREAD

**Issue by knobik** [Galarzaa90/NabBot#67]
![chrome_2017-11-14_14-39-53](https://user-images.githubusercontent.com/795254/32782820-eced475a-c949-11e7-84dc-5dc0863fdfe1.png)

```
2017-11-14 14:09:30,487:INFO: Command by Ekhzel in #glorious_bot (Exura Vita (Reddit)): /whois Ekhzel
In whois:
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/NabBot/cogs/tibia.py", line 59, in whois
    char = await get_character(name)
  File "/root/NabBot/utils/tibia.py", line 113, in get_character
    level = int(death["level"])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by Galarzaa90** [comment]
I had fixed this already, guess I brought it back when I switched to TibiaData. This is **rewrite** right?

**Comment by Tschis** [comment]
Based on the lines of code and packages, it is **rewrite** @Galarzaa90

**Comment by Galarzaa90** [comment]
@knobik It's fixed, for now those deaths are just ignored.

I need to make big changes in order to support those types of deaths, as everywhere where deaths are displayed, a level is required.

I also need to support multiple killer deaths, with TibiaData it should be way easier.
