### ISSUE TITLE
problem with aiohttp....

### ISSUE THREAD

**Issue by Kuhitacop** [Galarzaa90/NabBot#70]
Hello I have some problems with the pip install.
I'm running cmd as admin, I've set environment variables to path as python cmd is working in cmd.

Running from system32 folder:
https://gyazo.com/c03b309ce66b8611eea2e2c2267e64f5

Running from the bot folder:
https://gyazo.com/9bfbbe0b3bfe773c7ebb1d5cb2865cce

Running from the bot folder changing requests to request
https://gyazo.com/610c9c2b250962b17b528d51eca76fb6

Changing codepage to chcp 65001
https://gyazo.com/a1e67522706a0643a102bdc17f76eb2a

Python version:
https://gyazo.com/a03549ede935c1d49ac9aeddd74557f2

Any ideas?? I'm good in C and Visual Basic but never used Python and this shitty environments :S
Thanks brothers!

**Comment by Galarzaa90** [comment]
Try installing aiohttp on it's own
```
python -m pip install aiohttp
```

https://github.com/Rapptz/discord.py/issues/586

**Comment by Kuhitacop** [comment]
I got the same error...
https://gyazo.com/f4148e1ca545b8a6ba2b3f21c307881e
https://gyazo.com/0de1b50e57b7528f04ae283e5de29429

**Comment by Kuhitacop** [comment]
Solved:

py -3.6 -m pip install -U pip
py -3.6 -m pip install -U https://github.com/pypa/pip/archive/master.zip

Then try and install your packages in the same format.
For example:
py -3.6 -m pip install -U discord.py
