### ISSUE TITLE
/stalk sub commands

### ISSUE THREAD

**Issue by Sinsae** [Galarzaa90/NabBot#72]
I can't seam to get the command: /stalk addchar and /stalk addacc to work correctly.  I tried numerous times and it just doesnt reply anything, unless you use the wrong syntax. The correct syntax yields no reply and doesnt add the char to the users database at all ;[. Maybe not a bug and just a noob user. Thanks for sweet bot!

**Comment by Galarzaa90** [comment]
Going to assume you use master.
What's showing on console?

**Comment by Sinsae** [comment]
[image: Inline image 1]
Hopefully, this is what you meant...?
Thanks for the fast reply.

**Comment by Sinsae** [comment]
2017-12-02 20:50:09,154:INFO: Command by Sinsae (Chris) in PM: /stalk addchar @S
insae (Chris)#3644, Zaen
In stalk addchar:
  File "C:\Users\Extat\AppData\Local\Programs\Python\Python36-32\discord\ext\com
mands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Extat\AppData\Local\Programs\Python\Python36-32\mod.py", line 1
24, in add_char
    user_servers = get_user_servers(self.bot, user.id)
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Sinsae** [comment]
Also is that command only workable in DM to the bot? Because in my DM with it the other member user names don't show up, so do we just manually type in their full username?

**Comment by Sinsae** [comment]
GOOD NEWS 

I edited line 124 mod.py from: 
 user_servers = get_user_servers(self.bot, user.id)
 to
 user_servers = get_user_servers(self.bot, author.id)

Outcome: PROBLEM FIXED! ( I think, i finally got it working)

Very awesome bot man! Highly recommended! **«3**
