### ISSUE TITLE
bot isnt reading some stuff like jewels, plat coins, gold coins, grimleech quantities

### ISSUE THREAD

**Issue by kivex** [Galarzaa90/NabBot#73]
## Platform information
* **Operating system:** 
* **Python version:**
* **Repository branch:** master

## Bug information

I use png screenshots, some items stopped being read by the bot correctly after the update, any tips?

**Steps to reproduce:**: 

**Expected result:**

**Actual result:**

**Comment by Galarzaa90** [comment]
Hello @Nezune

**Comment by Galarzaa90** [comment]
Fixed in 29145c24d35fcb65f50d9dce316a4943c5f287a7, thanks @Nezune 👌

**Comment by Nezune** [comment]
poxa @Galarzaa90
