### ISSUE TITLE
scan_online_characters error

### ISSUE THREAD

**Issue by Zahedee** [Galarzaa90/NabBot#75]
## Platform information
* **Operating system:** Ubuntu 14.04
* **Python version:** 3.6.3
* **Repository branch:** rewrite

## Bug Information

Not really sure if it is a bug or not, but my log is getting filled with these messages every minute.

`2017-12-11 10:18:00,282:ERROR: scan_online_chars
Traceback (most recent call last):
  File "/root/NabBot/cogs/tracking.py", line 271, in scan_online_chars
    for x in currently_online]
  File "/root/NabBot/cogs/tracking.py", line 271, in <listcomp>
    for x in currently_online]
TypeError: 'Character' object is not subscriptable`

The level up announces and death announces works, but it's annoying when you want to search for something in the logs. 

Running the latest version of the rewrite branch.

**Comment by Galarzaa90** [comment]
It should be fixed now, thanks!
