### ISSUE TITLE
REQUEST: Item/creature Database Update

### ISSUE THREAD

**Issue by Sinsae** [Galarzaa90/NabBot#76]
NOT A BUG: 
Would it be possible to update the creature, item, and NPC database soon?
All the new creatures and items from the latest Tibia update doesn't exist in the current database file. Would be nice to have it! Thanks.

**Comment by Galarzaa90** [comment]
If you're using the master branch, then sadly, I can't update that database, as the script I was using for it stopped working.

I created a new script, but it requires making changes to make it compatible with the code, which I already did on the [rewrite branch](https://github.com/Galarzaa90/NabBot/tree/rewrite).

If you meant on the rewrite branch, yes I can update it, but information might still be partial as data is obtained from TibiaWiki.

**Comment by Sinsae** [comment]
You were exactly right on the Master version! Also exactly what I was hoping would happen, it be attached to tibia.wiki's site! Very sexy work man. It took me awhile to reinstall everything and figure it out again, but works like a charm! I wish I knew about the Rewrite-Branch sooner. **Thanks again for the help!**
