### ISSUE TITLE
/check on specific char breaks bot

### ISSUE THREAD

**Issue by Zahedee** [Galarzaa90/NabBot#77]
There seems to be an issue with the house ID for the house Tunnel Gardens 2 (Kazordoon). 

<img width="746" alt="vlurr" src="https://user-images.githubusercontent.com/34237700/33834761-58862bd6-de84-11e7-97c4-91fd6d32268c.png">

> 
> 2017-12-11 14:40:18,928:INFO: Command by Fritspizza in #glorious_bot (Exura Vita (Reddit)): /check vlurr
> 2017-12-11 14:40:19,138:ERROR: Exception in command: whois
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "/root/NabBot/cogs/tibia.py", line 67, in whois
>     char_string = self.get_char_string(char)
>   File "/root/NabBot/cogs/tibia.py", line 1524, in get_char_string
>     house_url = url_house.format(id=char.house["id"], world=char.world)
> KeyError: 'id'

**Comment by Galarzaa90** [comment]
This was fixed by PR #78, thanks @Tschis
