### ISSUE TITLE
[REQUEST] Stamina calculator!

### ISSUE THREAD

**Issue by Sinsae** [Galarzaa90/NabBot#79]
I was wondering if you could possibly add a feature to calculate the time until full stamina? There are a few websites with a simple calculator like tibia-stats.com. Would just be another nice tool in the bag. Thanks!
/stamina 38:14
It will take 25 hours and 28 minutes until full stamina.

**Comment by Galarzaa90** [comment]
I will try to do this this weekend, sounds easy and useful.

**Comment by Galarzaa90** [comment]
This has been implemented on the `rewrite` branch.

![image](https://user-images.githubusercontent.com/12865379/35185858-b7db44a6-fdc7-11e7-8223-d06ae127f751.png)
The footer also shows the time (in the viewer's timezone) at which you will have full stamina.

**Comment by Sinsae** [comment]
Thanks!!
