### ISSUE TITLE
/watched addguild problem + Request 

### ISSUE THREAD

**Issue by Sinsae** [Galarzaa90/NabBot#83]
**WATCHED GUILD**

For the world of Amera at least, there are a few of guilds that 'does not exist" when the command _/watched addguild_ is used.
 ex: 
/watched addguild Academy of Might and Magic
    (first on Amera's guild list seems to not exist).
----------------------------------------------------------------------------------------------------------------
**REQUEST**

This is a request from someone on my Discord server:
A command to check a server's downtime during a server save. It should start a timer when the server goes down, and report the tracked servers offline time duration to the command:  _/downtime <world>_

 _/downtime Amera_
Amera was offline for 7 minutes.
                   -or-
Amera was offline for 12 minutes - Higher chance of raids today!

**Comment by Galarzaa90** [comment]
That seems to be a problem with TibiaData, I will forward it to them.

**Comment by Galarzaa90** [comment]
This was a momentary problem with the API, I reported it to TibiaData's owner and by the time he read the email, the issue was not present anymore. So it was just a caching issue probably.

**Comment by Sinsae** [comment]
@Galarzaa90 
![example1](https://user-images.githubusercontent.com/34200276/39289806-2a3df1f8-48f3-11e8-9997-30446814cfdd.PNG)
![example2](https://user-images.githubusercontent.com/34200276/39289810-2ce83846-48f3-11e8-96d4-b10d78adf618.PNG)

This is the very first guild on the list in "Amera", and is still currently the first guild in "Solidera".
This is not the only guild that "does not exist" also ;/

**Comment by Sinsae** [comment]
I personally emailed them also. Idk.

**Comment by Sinsae** [comment]
I'm glad they responded to somebody, even if it was false hopes.

**Comment by Sinsae** [comment]
![proof](https://user-images.githubusercontent.com/34200276/39290973-fbd0d606-48f6-11e8-9836-e76249a9ea20.PNG)
This show's they exist even on **their** DB.. Even more confused..

**Comment by Galarzaa90** [comment]
Yes, I understand that the guild does exist, there seems to be something that making their parser not detect it *sometimes*.

![image](https://user-images.githubusercontent.com/12865379/39315335-4e8aa406-492b-11e8-8ed2-0aaaf672caf2.png)

I'm going to tell him about it again. If you can tell me the names of other guilds where the same is happening, that may help find a pattern for the bug.

**Comment by Sinsae** [comment]
Will do.. Thanks!
