### ISSUE TITLE
Guildstats.eu format error + Purge error

### ISSUE THREAD

**Issue by Sinsae** [Galarzaa90/NabBot#84]
_Re-write branch of course._

I'm not sure what the issue is, just see this in the  log, popping up a lot today:

> 2018-03-06 13:17:48,848:ERROR: get_guild_online: -IMPORTANT- guildstats.eu seems to have changed their websites format.

Then on the /purge command it initiates the purge, then hits an error:

> 2018-03-06 13:25:03,246:INFO: Command by Chris (Sinsae) in PM: /purge
2018-03-06 13:25:05,149:ERROR: Exception in command: purge
Traceback (most recent call last):
  File "C:\Users\Extat\AppData\Local\Programs\Python\Python36-32\discord\ext\com
mands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Extat\AppData\Local\Programs\Python\Python36-32\cogs\owner.py",
 line 289, in purge
    if char['name'] != row["name"]:
TypeError: 'Character' object is not subscriptable

Help and Thanks!

**Comment by Galarzaa90** [comment]
About the first issue, what command was called exactly? Can you show me some lines before and after that?

About, purge is a function I haven't mantained in a long time, I'm going to rewrite/delete it soon

**Comment by Sinsae** [comment]
There are no commands being given to it. It just shows that message in the CMD window approximately every 3 minutes or so. I'm not sure what triggers it.

**Comment by Sinsae** [comment]
I also redownloaded the whole rewrite.zip and replaced all files and replaced them, except the data folder. Im receiving the same message.

**Comment by Sinsae** [comment]
I have found the issue. It was probably how many people I had it track. on the watchedguild list, I literally added every guild in Amera that it could find. Maybe it was because how many requests it was getting from me?

**Comment by Galarzaa90** [comment]
Fixed the error thrown by `/purge`, I still wouldn't recommend using this command as it hasn't been mantained in a while. If used, create a backup of the database before use.
